# Generated by Django 5.1.7 on 2025-04-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showRoom', '0002_sales_car_title_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='car_title',
            new_name='car',
        ),
    ]
